"""followers

Revision ID: 280fd83b1d85
Revises: d2c37f41dd3e
Create Date: 2018-03-25 17:32:47.484614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280fd83b1d85'
down_revision = 'd2c37f41dd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
